from .env import require, require_float, require_int

CONVERSATION_HISTORY_LIMIT = require_int("CONVERSATION_HISTORY_LIMIT")
SUMMARIZE_MAX_MESSAGES = require_int("SUMMARIZE_MAX_MESSAGES")
CHECKPOINTER_ENABLED = require("CHECKPOINTER_ENABLED").lower() == "true"
SUMMARIZER_TEMPERATURE = require_float("SUMMARIZER_TEMPERATURE")
SUMMARIZER_MAX_TOKENS = require_int("SUMMARIZER_MAX_TOKENS")
CRITIQUE_TEMPERATURE = require_float("CRITIQUE_TEMPERATURE")
CRITIQUE_MAX_TOKENS = require_int("CRITIQUE_MAX_TOKENS")
DEFAULT_TEMPERATURE = require_float("DEFAULT_TEMPERATURE")
DEFAULT_MAX_TOKENS = require_int("DEFAULT_MAX_TOKENS")