from typing import Any, Dict, List, Optional, Protocol, Tuple
import uuid


class ProfilesRepositoryLike(Protocol):
    def get_profile_by_id(self, user_id: uuid.UUID) -> Optional[Any]: ...

    def get_or_create_profile(self, user_id: uuid.UUID, username: str) -> Tuple[uuid.UUID, bool]: ...

    def delete_profile(self, user_id: uuid.UUID) -> bool: ...


class ConversationsRepositoryLike(Protocol):
    def get_conversation_id_by_user(self, user_id: uuid.UUID) -> Optional[uuid.UUID]: ...

    def get_or_create_conversation_id(self, user_id: uuid.UUID) -> uuid.UUID: ...

    def touch_conversation(self, conversation_id: uuid.UUID) -> None: ...

    def get_summary(self, conversation_id: uuid.UUID) -> Optional[str]: ...

    def update_summary(self, conversation_id: uuid.UUID, summary: str) -> None: ...


class MessagesRepositoryLike(Protocol):
    def add_message(
        self,
        conversation_id: uuid.UUID,
        role: str,
        content: str,
        sources: Optional[List[Dict[str, Any]]] = None,
    ) -> None: ...

    def list_recent_messages(self, conversation_id: uuid.UUID, limit: int) -> List[Dict[str, Any]]: ...

    def count_messages(self, conversation_id: uuid.UUID) -> int: ...

    def clear_conversation(self, conversation_id: uuid.UUID) -> int: ...

    def invalidate_cache(self, conversation_id: uuid.UUID) -> None: ...
