from typing import Any, Dict, List, Optional, Protocol


class UsersRepositoryLike(Protocol):
    def delete_user_by_id(self, user_id: int) -> bool: ...


    def get_user_by_username(self, username: str) -> Optional[Any]: ...

    def create_user(self, username: str, hashed_password: str) -> int: ...


    def get_user_by_id(self, user_id: int) -> Optional[Any]: ...


    def get_user_id_by_username(self, username: str) -> Optional[int]: ...


    def set_password(self, user_id: int, hashed_password: str) -> None: ...


    def set_active(self, user_id: int, active: bool) -> None: ...


    def is_active(self, user_id: int) -> bool: ...


    def resolve_principal(self, user_id: int) -> Optional[Any]: ...


    def resolve_principal_by_username(self, username: str) -> Optional[Any]: ...


    def resolve_principal_by_token(self, token: str) -> Optional[Any]: ...


    def issue_token(self, user_id: int) -> str: ...


class ConversationsRepositoryLike(Protocol):
    def get_conversation_id_by_user(self, user_id: int) -> Optional[int]: ...

    def get_or_create_conversation_id(self, user_id: int) -> int: ...

    def touch_conversation(self, conversation_id: int) -> None: ...

    def get_summary(self, conversation_id: int) -> Optional[str]: ...

    def update_summary(self, conversation_id: int, summary: str) -> None: ...


    def delete_conversation(self, conversation_id: int) -> bool: ...

    def clear_conversations(self) -> int: ...


class MessagesRepositoryLike(Protocol):
    def add_message(
        self,
        conversation_id: int,
        role: str,
        content: str,
        sources: Optional[List[str]] = None,
    ) -> None: ...

    def list_recent_messages(self, conversation_id: int, limit: int) -> List[Dict[str, Any]]: ...

    def count_messages(self, conversation_id: int) -> int: ...

    def clear_conversation(self, conversation_id: int) -> int: ...