from typing import Any, Dict, List, Optional, Protocol


class UsersRepositoryLike(Protocol):
    def get_user_by_id(self, user_id: int) -> Optional[Any]: ...

    def get_user_by_username(self, username: str) -> Optional[Any]: ...

    def get_or_create_user_id(self, username: str, hashed_password: str) -> int: ...

    def delete_user_by_id(self, user_id: int) -> bool: ...


class ConversationsRepositoryLike(Protocol):
    def get_conversation_id_by_user(self, user_id: int) -> Optional[int]: ...

    def get_or_create_conversation_id(self, user_id: int) -> int: ...

    def touch_conversation(self, conversation_id: int) -> None: ...

    def get_summary(self, conversation_id: int) -> Optional[str]: ...

    def update_summary(self, conversation_id: int, summary: str) -> None: ...


class MessagesRepositoryLike(Protocol):
    def add_message(
        self,
        conversation_id: int,
        role: str,
        content: str,
        sources: Optional[List[Dict[str, Any]]] = None,
    ) -> None: ...

    def list_recent_messages(self, conversation_id: int, limit: int) -> List[Dict[str, Any]]: ...

    def count_messages(self, conversation_id: int) -> int: ...

    def clear_conversation(self, conversation_id: int) -> int: ...