from .env import require, require_float, require_int

CONTEXT_WINDOW_LIMIT_FRACTION = require_float("CONTEXT_WINDOW_LIMIT_FRACTION")

SUMMARIZER_MODEL = require("SUMMARIZER_MODEL")
SUMMARIZER_TEMPERATURE = require_float("SUMMARIZER_TEMPERATURE")
SUMMARIZER_MAX_TOKENS = require_int("SUMMARIZER_MAX_TOKENS")

CRITIQUE_MODEL = require("CRITIQUE_MODEL")
CRITIQUE_TEMPERATURE = require_float("CRITIQUE_TEMPERATURE")
CRITIQUE_MAX_TOKENS = require_int("CRITIQUE_MAX_TOKENS")

RESPONSE_TEMPERATURE = require_float("INITIAL_RESPONSE_TEMPERATURE")
RESPONSE_MAX_TOKENS = require_int("INITIAL_RESPONSE_MAX_TOKENS")
RESPONSE_MODEL = require("INITIAL_RESPONSE_MODEL")
