import os

from .env import require, require_float, require_int, get_int, get_str, require_secret

OPENROUTER_API_KEY = require_secret("OPENROUTER_API_KEY")
OPENROUTER_BASE_URL = require("OPENROUTER_BASE_URL")
# OPENROUTER_HTTP_REFERER = os.getenv("OPENROUTER_HTTP_REFERER", "")
# OPENROUTER_SITE_TITLE = os.getenv("OPENROUTER_SITE_TITLE", "")

DATABASE_URL = require("DATABASE_URL")
# DB_POOL_SIZE = require_int("DB_POOL_SIZE")
# DB_MAX_OVERFLOW = require_int("DB_MAX_OVERFLOW")

CHAT_CACHE_REDIS_URL = require("CHAT_CACHE_REDIS_URL")
SEMANTIC_CACHE_THRESHOLD = require_float("SEMANTIC_CACHE_THRESHOLD")
CACHE_INDEX_NAME = require("CACHE_INDEX_NAME")
# CHAT_CACHE_TTL_SECONDS = require_int("CHAT_CACHE_TTL_SECONDS")
# CHAT_CACHE_KEY_PREFIX = require("CHAT_CACHE_KEY_PREFIX")

# Token blacklist Redis settings
# TOKEN_BLACKLIST_ENABLED = get_int("TOKEN_BLACKLIST_ENABLED", 1)  # Enabled by default
# TOKEN_BLACKLIST_PREFIX = get_str("TOKEN_BLACKLIST_PREFIX", "token:blacklist:")

RETRIES_PER_MODEL = require_int("RESPONSE_RETRIES_PER_MODEL")

EMBEDDING_MODEL = require("EMBEDDING_MODEL")
EMBEDDING_FALLBACK_MODEL = require("EMBEDDING_FALLBACK_MODEL")
EMBEDDING_DIM = require_int("EMBEDDING_DIM")

RAG_WORKING_DIR = os.getenv("WORKING_DIR", "data/processed")
RAG_QUERY_MAX_TOKENS = require_int("RAG_QUERY_MAX_TOKENS")
RAG_QUERY_TOP_K = require_int("RAG_QUERY_TOP_K")
