from .conversation import CONVERSATION_HISTORY_LIMIT, SUMMARIZE_MAX_MESSAGES
from .infrastructure import (
    CHAT_CACHE_KEY_PREFIX,
    CHAT_CACHE_REDIS_URL,
    CHAT_CACHE_TTL_SECONDS,
    DATABASE_URL,
    DB_MAX_OVERFLOW,
    DB_POOL_SIZE,
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    OPENROUTER_HTTP_REFERER,
    OPENROUTER_SITE_TITLE,
)
from .prompts import CRITIQUE_PROMPT, RAG_FAILURE_RESPONSE, REFINEMENT_PROMPT, SUMMARY_PROMPT, SYSTEM_PROMPT
from .rag import EMBED_HOST, EMBED_MODEL, EMBEDDING_DIM, LLM_MODEL, MAX_TOKENS, RAG_WORKING_DIR, _raw_embed
from .security import (
    AUTH_PASSWORD_ITERATIONS,
    AUTH_PASSWORD_SALT_BYTES,
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES,
    JWT_ALGORITHM,
    JWT_SECRET_KEY,
)


class Config:
    JWT_SECRET_KEY = JWT_SECRET_KEY
    JWT_ALGORITHM = JWT_ALGORITHM
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES = JWT_ACCESS_TOKEN_EXPIRE_MINUTES
    AUTH_PASSWORD_ITERATIONS = AUTH_PASSWORD_ITERATIONS
    AUTH_PASSWORD_SALT_BYTES = AUTH_PASSWORD_SALT_BYTES

__all__ = [
    "Config",
    "AUTH_PASSWORD_ITERATIONS",
    "AUTH_PASSWORD_SALT_BYTES",
    "CHAT_CACHE_KEY_PREFIX",
    "CHAT_CACHE_REDIS_URL",
    "CHAT_CACHE_TTL_SECONDS",
    "CONVERSATION_HISTORY_LIMIT",
    "CRITIQUE_PROMPT",
    "DATABASE_URL",
    "DB_MAX_OVERFLOW",
    "DB_POOL_SIZE",
    "EMBEDDING_DIM",
    "EMBED_HOST",
    "EMBED_MODEL",
    "JWT_ACCESS_TOKEN_EXPIRE_MINUTES",
    "JWT_ALGORITHM",
    "JWT_SECRET_KEY",
    "LLM_MODEL",
    "MAX_TOKENS",
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_HTTP_REFERER",
    "OPENROUTER_SITE_TITLE",
    "RAG_FAILURE_RESPONSE",
    "RAG_WORKING_DIR",
    "REFINEMENT_PROMPT",
    "SUMMARY_PROMPT",
    "SUMMARIZE_MAX_MESSAGES",
    "SYSTEM_PROMPT",
    "_raw_embed",
]