from .conversation import CONVERSATION_HISTORY_LIMIT, SUMMARIZE_MAX_MESSAGES
from .infrastructure import (
    CHAT_CACHE_KEY_PREFIX,
    CHAT_CACHE_REDIS_URL,
    CHAT_CACHE_TTL_SECONDS,
    DATABASE_URL,
    DB_MAX_OVERFLOW,
    DB_POOL_SIZE,
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    OPENROUTER_HTTP_REFERER,
    OPENROUTER_SITE_TITLE,
)
from .prompts import CRITIQUE_PROMPT, RAG_FAILURE_RESPONSE, REFINEMENT_PROMPT, SUMMARY_PROMPT, SYSTEM_PROMPT
from .rag import EMBED_MODEL, EMBEDDING_DIM, LLM_MODEL, MAX_TOKENS, RAG_WORKING_DIR
from .security import QUERY_RATE_LIMIT, QUERY_RATE_WINDOW_SECONDS


class Config:
    QUERY_RATE_LIMIT = QUERY_RATE_LIMIT
    QUERY_RATE_WINDOW_SECONDS = QUERY_RATE_WINDOW_SECONDS

__all__ = [
    "Config",
    "CHAT_CACHE_KEY_PREFIX",
    "CHAT_CACHE_REDIS_URL",
    "CHAT_CACHE_TTL_SECONDS",
    "CONVERSATION_HISTORY_LIMIT",
    "CRITIQUE_PROMPT",
    "DATABASE_URL",
    "DB_MAX_OVERFLOW",
    "DB_POOL_SIZE",
    "EMBEDDING_DIM",
    "EMBED_MODEL",
    "LLM_MODEL",
    "MAX_TOKENS",
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_HTTP_REFERER",
    "OPENROUTER_SITE_TITLE",
    "QUERY_RATE_LIMIT",
    "QUERY_RATE_WINDOW_SECONDS",
    "RAG_FAILURE_RESPONSE",
    "RAG_WORKING_DIR",
    "REFINEMENT_PROMPT",
    "SUMMARY_PROMPT",
    "SUMMARIZE_MAX_MESSAGES",
    "SYSTEM_PROMPT",
]