from .conversation import CONVERSATION_HISTORY_LIMIT, SUMMARIZE_MAX_MESSAGES
from .infrastructure import (
    CHAT_CACHE_KEY_PREFIX,
    CHAT_CACHE_REDIS_URL,
    CHAT_CACHE_TTL_SECONDS,
    DATABASE_URL,
    DB_MAX_OVERFLOW,
    DB_POOL_SIZE,
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    OPENROUTER_HTTP_REFERER,
    OPENROUTER_SITE_TITLE,
)
from .prompts import CRITIQUE_PROMPT, REFINEMENT_PROMPT, SUMMARY_PROMPT, SYSTEM_PROMPT
from .rag import EMBED_HOST, EMBED_MODEL, EMBEDDING_DIM, LLM_MODEL, MAX_TOKENS, RAG_WORKING_DIR, _raw_embed
from .security import (
    AUTH_PASSWORD_ITERATIONS,
    AUTH_PASSWORD_SALT_BYTES,
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES,
    JWT_ALGORITHM,
    JWT_SECRET_KEY,
)


class Config:
    # RAG and model settings
    RAG_WORKING_DIR = RAG_WORKING_DIR
    _raw_embed = _raw_embed
    EMBED_HOST = EMBED_HOST
    LLM_MODEL = LLM_MODEL
    EMBED_MODEL = EMBED_MODEL
    EMBEDDING_DIM = EMBEDDING_DIM
    MAX_TOKENS = MAX_TOKENS

    # LLM and infrastructure integrations
    OPENROUTER_API_KEY = OPENROUTER_API_KEY
    OPENROUTER_BASE_URL = OPENROUTER_BASE_URL
    OPENROUTER_HTTP_REFERER = OPENROUTER_HTTP_REFERER
    OPENROUTER_SITE_TITLE = OPENROUTER_SITE_TITLE

    # Persistent storage settings
    DATABASE_URL = DATABASE_URL
    DB_POOL_SIZE = DB_POOL_SIZE
    DB_MAX_OVERFLOW = DB_MAX_OVERFLOW

    # Authentication settings
    AUTH_PASSWORD_ITERATIONS = AUTH_PASSWORD_ITERATIONS
    AUTH_PASSWORD_SALT_BYTES = AUTH_PASSWORD_SALT_BYTES

    # Conversation cache and history
    CHAT_CACHE_REDIS_URL = CHAT_CACHE_REDIS_URL
    CHAT_CACHE_TTL_SECONDS = CHAT_CACHE_TTL_SECONDS
    CHAT_CACHE_KEY_PREFIX = CHAT_CACHE_KEY_PREFIX
    CONVERSATION_HISTORY_LIMIT = CONVERSATION_HISTORY_LIMIT

    # JWT settings
    JWT_SECRET_KEY = JWT_SECRET_KEY
    JWT_ALGORITHM = JWT_ALGORITHM
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES = JWT_ACCESS_TOKEN_EXPIRE_MINUTES

    # Prompt templates
    SYSTEM_PROMPT = SYSTEM_PROMPT
    CRITIQUE_PROMPT = CRITIQUE_PROMPT
    REFINEMENT_PROMPT = REFINEMENT_PROMPT

    # Summarization settings
    SUMMARIZE_MAX_MESSAGES = SUMMARIZE_MAX_MESSAGES
    SUMMARY_PROMPT = SUMMARY_PROMPT


__all__ = ["Config"]