import os

CONVERSATION_HISTORY_LIMIT = int(os.getenv("CONVERSATION_HISTORY_LIMIT", "50"))

SUMMARIZE_MAX_MESSAGES = int(os.getenv("SUMMARIZE_MAX_MESSAGES", "20"))

CHECKPOINTER_ENABLED = os.getenv("CHECKPOINTER_ENABLED", "false").lower() == "true"

SUMMARIZER_TEMPERATURE = float(os.getenv("SUMMARIZER_TEMPERATURE", "0.1"))
SUMMARIZER_MAX_TOKENS = int(os.getenv("SUMMARIZER_MAX_TOKENS", "300"))

CRITIQUE_TEMPERATURE = float(os.getenv("CRITIQUE_TEMPERATURE", "0.0"))
CRITIQUE_MAX_TOKENS = int(os.getenv("CRITIQUE_MAX_TOKENS", "600"))

DEFAULT_TEMPERATURE = float(os.getenv("DEFAULT_TEMPERATURE", "0.1"))
DEFAULT_MAX_TOKENS = int(os.getenv("DEFAULT_MAX_TOKENS", "800"))