from .env import require, require_int

AUTH_PASSWORD_ITERATIONS = require_int("AUTH_PASSWORD_ITERATIONS")
AUTH_PASSWORD_SALT_BYTES = require_int("AUTH_PASSWORD_SALT_BYTES")

JWT_SECRET_KEY = require("JWT_SECRET_KEY")
JWT_ALGORITHM = require("JWT_ALGORITHM")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = require_int("JWT_ACCESS_TOKEN_EXPIRE_MINUTES")